Networked Systems:
- changed-files:
  - any-glob-to-any-file: notes/2024-2025/computing_science/networked_systems/**

Database Systems:
- changed-files:
  - any-glob-to-any-file: notes/2024-2025/computing_science/database_systems/**

Professional Software Development:
- changed-files:
  - any-glob-to-any-file: notes/2024-2025/computing_science/professional_software_development/**

Data Fundamentals:
- changed-files:
  - any-glob-to-any-file: notes/2024-2025/computing_science/data_fundamentals/**

Systems Programming:
- changed-files:
  - any-glob-to-any-file: notes/2024-2025/computing_science/systems_programming/**

Text as Data:
- changed-files:
  - any-glob-to-any-file: notes/2024-2025/computing_science/text_as_data/**

Github Actions:
- changed-files:
  - any-glob-to-any-file: .github/**
