Database Systems:
- changed-files:
  - any-glob-to-any-file: notes/year_3/computing_science/database_systems/**

Systems Programming:
- changed-files:
  - any-glob-to-any-file: notes/year_3/computing_science/systems_programming/**

Github Actions:
- changed-files:
  - any-glob-to-any-file: .github/**
