name: CI

on:
  pull_request:
    paths:
    - '**/*.typ'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: typst-community/setup-typst@v4

    - name: Build Typst
      run: make compile
