name: "Compile Action"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run make compile
        run: make compile
    
      - uses: EndBug/add-and-commit@v9
        with:
            message: Show GitHub logo
            committer_name: GitHub Actions
            committer_email: 41898282+github-actions[bot]@users.noreply.github.com
                